# src/AppBundle/Resources/config/serialization.yml
SportRadar\CalendarBundle\Entity\Sport:
    attributes:
        id:
            groups: ['sport','event']
        title:
            groups: ['sport','event']
        events:
            groups: ['sport','event']
SportRadar\CalendarBundle\Entity\Event:
    attributes:
        id:
            groups: ['event','sport']
        date:
            groups: ['event','sport']
        city:
            groups: ['event','sport']
        